darcs add ReadMe.txt
darcs add ArrowWrap.hs
darcs add Setup.hs
darcs add Euterpea.cabal
darcs add MakeDarcs.bat
darcs add License

darcs add Euterpea/Examples/EuterpeaExamples.lhs
darcs add Euterpea/Examples/NewResolutions.lhs
darcs add Euterpea/Examples/UIExamples.hs
darcs add Euterpea/Examples/MUIExamples.lhs
darcs add Euterpea/Examples/SoundCheck.hs
darcs add Euterpea/Examples/Ssf.lhs
darcs add Euterpea/Examples/EnableGUI.hs

darcs add HSoM/Preface.lhs
darcs add HSoM/Intro.lhs
darcs add HSoM/Music.lhs
darcs add HSoM/Poly.lhs
darcs add HSoM/Interlude.lhs
darcs add HSoM/Syntax.lhs
darcs add HSoM/MoreMusic.lhs
darcs add HSoM/QualifiedTypes.lhs
darcs add HSoM/Performance.lhs
darcs add HSoM/SelfSimilar.lhs
darcs add HSoM/Induction.lhs
darcs add HSoM/Algebra.lhs
darcs add HSoM/LSystems.lhs
darcs add HSoM/RandomMusic.lhs
darcs add HSoM/ToMidi.lhs
darcs add HSoM/IO.lhs
darcs add HSoM/MUI.lhs
darcs add HSoM/Signals.lhs
darcs add HSoM/SigFuns.lhs
darcs add HSoM/SpectrumAnalysis.lhs
darcs add HSoM/Additive.lhs
darcs add HSoM/Class-tour.lhs
darcs add HSoM/Bitans.lhs
darcs add HSoM/Patterns.lhs
darcs add HSoM/myFormat.fmt
darcs add HSoM/HSoM.bib
darcs add HSoM/MakeCode.bat
darcs add HSoM/MakeTex.bat

darcs add Control/CCA/ArrowP.lhs
darcs add Control/SF/Arrow.lhs

darcs add Euterpea.lhs
darcs add Euterpea/Examples/Interlude.hs
darcs add Euterpea/Examples/LSystems.hs
darcs add Euterpea/Examples/RandomMusic.hs
darcs add Euterpea/Examples/SelfSimilar.hs
darcs add Euterpea/IO/Audio/Basics.as
darcs add Euterpea/IO/Audio/CSoundGenerators.as
darcs add Euterpea/IO/Audio/IO.hs
darcs add Euterpea/IO/Audio/Render.hs
darcs add Euterpea/IO/Audio/Types.hs
darcs add Euterpea/IO/MIDI/MidiIO.lhs
darcs add Euterpea/IO/MIDI/FromMidi.hs
darcs add Euterpea/IO/MIDI/GeneralMidi.hs
darcs add Euterpea/IO/MIDI/ToMidi.hs
darcs add Euterpea/IO/MUI/Signal.lhs
darcs add Euterpea/IO/MUI/SOE.hs
darcs add Euterpea/IO/MUI/UIMonad.lhs
darcs add Euterpea/IO/MUI/Widget.lhs
darcs add Euterpea/IO/MUI.hs
darcs add Euterpea/Music/Note/MoreMusic.hs
darcs add Euterpea/Music/Note/Music.hs
darcs add Euterpea/Music/Note/Performance.hs
darcs add Euterpea/Music/Signal/Additive.hs
darcs add Euterpea/Music/Signal/SigFuns.hs
darcs add Euterpea/Music/Signal/SpectrumAnalysis.hs

darcs add System/Random/Distributions.hs
